schemaVersion: 2.1.0
metadata:
  name: ansible-demo
  namespace: emmanuelbm-dev
attributes:
  .che/che-theia-plugins.yaml: |
    - id: ms-python/python/latest
      override:
        sidecar: {}
    - id: redhat/vscode-yaml/latest
      override:
        sidecar: {}
    - id: redhat/vscode-xml/latest
      override:
        sidecar: {}
    - id: vscode/typescript-language-features/latest
      override:
        sidecar: {}
    - id: bmewburn/vscode-intelephense-client/latest
      override:
        sidecar: {}
  .vscode/extensions.json: |-
    {
      "recommendations": [
        "ms-python/python",
        "redhat/vscode-yaml",
        "redhat/vscode-xml",
        "vscode/typescript-language-features",
        "bmewburn/vscode-intelephense-client"
      ]
    }
  metadata-name-field: generateName
  metadata-name-original-value: ansible-demo
projects:
  - attributes:
      source-origin: branch
    git:
      checkoutFrom:
        revision: master
      remotes:
        origin: 'https://github.com/emmanuel-oginni/ansible-examples'
    name: demopoc
components:
  - container:
      args:
        - tail
        - '-f'
        - /dev/null
      image: 'quay.io/nmalvankar/crw-ansible-rh-secure:2.12'
      memoryLimit: 512M
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: venv
          path: /home/jboss/.venv
    name: ansible
  - name: venv
    volume: {}
