schemaVersion: 2.1.0
metadata:
  name: ansible-demo
  namespace: emmagine-dev
attributes:
  .che/che-theia-plugins.yaml: |
    - id: ms-python/python/latest
      override:
        sidecar: {}
    - id: redhat/vscode-yaml/latest
      override:
        sidecar: {}
    - id: redhat/vscode-xml/latest
      override:
        sidecar: {}
    - id: vscode/typescript-language-features/latest
      override:
        sidecar: {}
    - id: bmewburn/vscode-intelephense-client/latest
      override:
        sidecar: {}
  .vscode/extensions.json: |-
    {
      "recommendations": [
        "ms-python/python",
        "redhat/vscode-yaml",
        "redhat/vscode-xml",
        "vscode/typescript-language-features",
        "bmewburn/vscode-intelephense-client"
      ]
    }
  controller.devfile.io/devworkspace-config:
    name: devworkspace-config
    namespace: crw
  controller.devfile.io/scc: container-build
  controller.devfile.io/storage-type: common
  metadata-name-field: generateName
  metadata-name-original-value: ansible-demo

components:
  - attributes:
      che-code.eclipse.org/contribute-cpuLimit: true
      che-code.eclipse.org/contribute-cpuRequest: true
      che-code.eclipse.org/contribute-memoryLimit: true
      che-code.eclipse.org/contribute-memoryRequest: true
      che-code.eclipse.org/contribute-volume-mount/checode: /checode
      che-code.eclipse.org/contributed-container: ansible
      che-code.eclipse.org/original-memoryLimit: 512M
    container:
      args:
        - tail
        - '-f'
        - /dev/null
      command:
        - /checode/entrypoint-volume.sh
      cpuLimit: 500m
      cpuRequest: 30m
      endpoints:
        - attributes:
            contributed-by: che-code.eclipse.org
            cookiesAuthEnabled: true
            discoverable: false
            type: main
            urlRewriteSupported: true
          exposure: public
          name: che-code
          path: '?tkn=eclipse-che'
          protocol: https
          secure: false
          targetPort: 3100
        - attributes:
            contributed-by: che-code.eclipse.org
            discoverable: false
            urlRewriteSupported: true
          exposure: public
          name: code-redirect-1
          protocol: http
          targetPort: 13131
        - attributes:
            contributed-by: che-code.eclipse.org
            discoverable: false
            urlRewriteSupported: true
          exposure: public
          name: code-redirect-2
          protocol: http
          targetPort: 13132
        - attributes:
            contributed-by: che-code.eclipse.org
            discoverable: false
            urlRewriteSupported: true
          exposure: public
          name: code-redirect-3
          protocol: http
          targetPort: 13133
      env:
        - name: CHE_DASHBOARD_URL
          value: 'https://devspaces.apps.sandbox.x8i5.p1.openshiftapps.com'
        - name: CHE_PLUGIN_REGISTRY_URL
          value: 'https://devspaces.apps.sandbox.x8i5.p1.openshiftapps.com/plugin-registry/v3'
        - name: CHE_PLUGIN_REGISTRY_INTERNAL_URL
          value: 'http://plugin-registry.crw.svc:8080/v3'
        - name: OPENVSX_REGISTRY_URL
          value: ''
      image: 'quay.io/nmalvankar/crw-ansible-rh-secure:2.12'
      memoryLimit: 1.59G
      memoryRequest: 256Mi
      mountSources: true
      sourceMapping: /projects
      volumeMounts:
        - name: venv
          path: /home/jboss/.venv
        - name: checode
          path: /checode
    name: ansible
  - name: venv
    volume: {}
